"use client";

import { useInView, motion, useMotionValue, useTransform, animate } from "motion/react";
import React, { useEffect, useRef } from "react";

interface StatItem {
  label: string;
  value: number;
  suffix: string;
  description: string;
}

const stats: StatItem[] = [
  {
    label: "Invoices Created",
    value: 50000,
    suffix: "+",
    description: "Generated by users worldwide",
  },
  {
    label: "Time Saved",
    value: 98,
    suffix: "%",
    description: "Faster than manual invoicing",
  },
  {
    label: "Templates",
    value: 12,
    suffix: "+",
    description: "Professional designs available",
  },
  {
    label: "Always Free",
    value: 100,
    suffix: "%",
    description: "No hidden costs, ever",
  },
];

function AnimatedNumber({ value, suffix }: { value: number; suffix: string }) {
  const ref = useRef<HTMLSpanElement>(null);
  const isInView = useInView(ref, { once: true, margin: "-100px" });
  const motionValue = useMotionValue(0);
  const rounded = useTransform(motionValue, (latest) => {
    if (value >= 1000) {
      return `${Math.round(latest / 1000)}k`;
    }
    return Math.round(latest).toString();
  });

  useEffect(() => {
    if (isInView) {
      animate(motionValue, value, {
        duration: 2,
        ease: "easeOut",
      });
    }
  }, [isInView, motionValue, value]);

  return (
    <span ref={ref} className="flex items-baseline gap-0.5">
      <motion.span className="instrument-serif text-foreground text-4xl font-normal tracking-tight sm:text-5xl">
        {rounded}
      </motion.span>
      <span className="text-primary instrument-serif text-2xl sm:text-3xl">{suffix}</span>
    </span>
  );
}

const Stats = () => {
  return (
    <section className="border-b border-dashed">
      <div className="grid grid-cols-2 sm:grid-cols-4">
        {stats.map((stat, index) => (
          <motion.div
            key={stat.label}
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: "-50px" }}
            transition={{ duration: 0.5, delay: index * 0.1, ease: "easeOut" }}
            className="flex flex-col gap-1.5 border-b border-dashed p-6 sm:border-b-0 sm:border-r last:sm:border-r-0 [&:nth-child(odd)]:border-r sm:[&:nth-child(odd)]:border-r"
          >
            <AnimatedNumber value={stat.value} suffix={stat.suffix} />
            <span className="jetbrains-mono text-foreground text-xs font-semibold tracking-tight">
              {stat.label}
            </span>
            <span className="jetbrains-mono text-muted-foreground text-[10px] leading-relaxed tracking-tight">
              {stat.description}
            </span>
          </motion.div>
        ))}
      </div>
    </section>
  );
};

export default Stats;
